apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-backend
  ports:
    - port: 8000
      targetPort: {{ .Values.backend.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-frontend
  ports:
    - port: 80
      targetPort: {{ .Values.frontend.port }}
